<?php

namespace AppBundle\Repository;

/**
 * UploadDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadDataRepository extends \Doctrine\ORM\EntityRepository
{
}
